ktor:
  application:
    modules:
      - io.fellowup.infrastructure.ApplicationKt.module
  deployment:
    port: 8080

oauth:
  auth-url: "${APP_FELLOW_UP_OAUTH_AUTH_URL}:http://localhost:8282/realms/fellow_up/protocol/openid-connect/auth"
  redirect-url: "${APP_FELLOW_UP_OAUTH_REDIRECT_URL}:http://localhost:8080/token"
  access-token-url: "${APP_FELLOW_UP_ACCESS_TOKEN_URL}:http://localhost:8282/realms/fellow_up/protocol/openid-connect/token"
  client-id: "${APP_FELLOW_UP_CLIENT_ID}:app_fellow_up"
  secret: "${APP_FELLOW_UP_SECRET}:y8h6R7eMtQky3o4DAcHeiyGq3Y"
  logout:
    url: "${APP_FELLOW_UP_LOG_OUT}:http://localhost:8282/realms/fellow_up/protocol/openid-connect/logout"

jwt:
  jwk-url: "${APP_FELLOW_UP_JWK_URL}:http://localhost:8282/realms/fellow_up/protocol/openid-connect/certs"
  issuer: "${APP_FELLOW_UP_ISSUER}:http://localhost:8282/realms/fellow_up"

db:
  jdbcUrl: "${APP_FELLOW_UP_DB_URL}:jdbc:postgresql://localhost:5432/app_fellow_up?serverTimezone=UTC"
  user: "${APP_FELLOW_UP_DB_USER}:app_fellow_up"
  password: "${APP_FELLOW_UP_DB_PASS}:app_fellow_up"
  schema: "${APP_FELLOW_UP_DB_SCHEMA}:public"
  keycloak:
    jdbcUrl: "${APP_FELLOW_UP_KC_DB_URL}:jdbc:postgresql://localhost:5432/keycloak?serverTimezone=UTC"
    user: "${APP_FELLOW_UP_KC_DB_USER}:app_fellow_up"
    password: "${APP_FELLOW_UP_KC_DB_PASS}:app_fellow_up"
    schema: "${APP_FELLOW_UP_KC_DB_SCHEMA}:public"

kafka:
  bootstrapServers: "${APP_FELLOW_UP_KAFKA_SERVERS}:localhost:9092"
  groupId: "${APP_FELLOW_UP_KAFKA_GROUP_ID}:io-fellow-up-backend-server"
  clientName: "${APP_FELLOW_YP_KAFKA_CLIENT_NAME}:io-fellow-up-backend-server"
